
version: '3.7'

networks:
  network1:
    name: jenkins-network
    external: true

services:
  minio:
    image: jenkinsci/blueocean:latest
    environment:
      - DOCKER_TLS_CERTDIR: /certs
    restart: always
    privileged: true
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /mydata/jenkins/home:/var/jenkins_home
      - /mydata/jenkins/maven:/usr/local/maven
      - /mydata/jenkins/certs:/certs/client
    networks:
      - network1
    ports:
        - "8080:8080" 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]